services:
  # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 89:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: thewall_db
      MYSQL_USER: thewall_user
      MYSQL_PASSWORD: TheWall123!
      MYSQL_ROOT_PASSWORD: TheWall123!
    ports:
      - 3309:3306
    volumes:
      - ./docker/sql/:/docker-entrypoint-initdb.d

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: thewall_user
      PMA_PASSWORD: TheWall123!
    ports:
      - "1089:80"

volumes:
  mysqldata:
